# Generated by Django 4.0.1 on 2022-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='um',
            field=models.CharField(max_length=10),
        ),
    ]
