# Generated by Django 4.0.1 on 2022-02-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shoppinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
