# Generated by Django 4.0.1 on 2022-02-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('users', '0003_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.companies'),
        ),
    ]
