# Generated by Django 4.0.1 on 2022-02-28 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_produs', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cantitate', models.IntegerField()),
                ('um', models.CharField(max_length=10)),
                ('expiration_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
