# Generated by Django 4.0.1 on 2022-03-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='marca',
        ),
    ]
