# Generated by Django 4.0.1 on 2022-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='recur',
            field=models.BooleanField(default=True),
        ),
    ]
