# Generated by Django 4.0.1 on 2022-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_minqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='necesar',
            field=models.IntegerField(default=0),
        ),
    ]
