# Generated by Django 4.0.1 on 2022-03-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
